name: CI
##
# Add the line below to README.md and the badge will come alive when the repo is public.
# [![CI](https://github.com/TheJacksonLaboratory/hpo-toolkit/workflows/CI/badge.svg)](https://github.com/TheJacksonLaboratory/hpo-toolkit/actions/workflows/python_ci.yml)

on:
    push:
      branches: [ development ]
    pull_request:
      branches: [ main, development ]

jobs:
    build:
      runs-on: ${{ matrix.os }}

      strategy:
        fail-fast: false
        matrix:
          os: [ windows-latest, macOS-latest, ubuntu-latest ]
          python: [ "3.6", "3.8", "3.10", "3.11" ]

      steps:
        - uses: actions/checkout@v2
        - name: Initialize Python ${{ matrix.python }}
          uses: actions/setup-python@v4.3.1
          with:
            python-version: ${{ matrix.python }}
        - name: Install package
          run: |
            # python -m pip install --upgrade pip
            pip install .
        - name: Run Tox tests
          run: |
            python -m pip install -U tox
            tox run